### PR TITLE
Remove duplication notification, and update subject and body

### PR DESCRIPTION
**Pull request by onedr0p**
This PR removes being notified twice when a service is updated, also I've updated the subject and body of the notification to be cleaner.

Let me know what you think. Thanks!

### CODE REVIEW

**Review by bram-pkg — APPROVED** [review]

**Comment by onedr0p** [comment]
oh hai, lul wut

**Comment by bram-pkg** [comment]
I could not merge it since your repository was deleted.

**Comment by onedr0p** [comment]
8 months later...

**Comment by bram-pkg** [comment]
Yes, sorry. I have been busy with my study.

**Pull request closed without merging**
